import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";

// Charger les polices locales depuis public/Fonts
const nohemi = localFont({
  src: "../public/Fonts/Nohemi/NohemiMedium.ttf", // Ajustez le nom exact du fichier ttf/woff2
  variable: "--font-nohemi-medium",
});

const nohemiRegular = localFont({
  src: "../public/Fonts/Nohemi/NohemiRegular.ttf", // Ajustez le chemin vers Delight
  variable: "--font-nohemi-regular",
  display: "swap",
});
const montserrat = Montserrat({
  variable: "--Montserrat",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${nohemi.variable} ${nohemiRegular.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col portfolio-bg">{children}</body>
    </html>
  );
}
